### ISSUE TITLE
Consider limiting faucet requests to `CELO` tokens (no `cStables` or other 3rd-party tokens)

### ISSUE THREAD

**Issue by arthurgousset** [celo-org/faucet#165]
### Describe the feature you would like

Context: [Faucet for testnet Mento stables](https://forum.celo.org/t/faucet-for-testnet-mento-stables/7719)

```[tasklist]
### Tasks
- [ ] https://github.com/celo-org/faucet/issues/184
- [ ] https://github.com/celo-org/faucet/issues/185
- [ ] https://github.com/celo-org/faucet/issues/186
- [ ] https://github.com/celo-org/faucet/issues/187
```

**Comment by aaronmgdr** [comment]
on second thought we should not do this until dango is decommisioned as on dango its pretty hard to get mento tokens

**Comment by aaronmgdr** [comment]
removing from milestone

**Comment by lvpeschke** [comment]
> on second thought we should not do this until dango is decommisioned as on dango its pretty hard to get mento tokens

Dango is decommissioned: #194.

**Comment by BenraouaneSoufiane** [comment]
@aaronmgdr I'm going to work on this, when the PR will reviewed???

**Comment by temitopeohassan** [comment]
@aaronmgdr Hello, I've read the contributing process and I would like to know how to be assigned this issue if possible please 
Thank you

**Comment by vortex-hue** [comment]
Hi @aaronmgdr, I'd like to know if this task involves resolving issue 184 ad 186 only? or it's a separate tasks, and is it under the scout game epic tag? please can I get assigned to it, and I'd make a draft pr within 5days after being assigned, thanks.

**Comment by aaronmgdr** [comment]
done
